package uk.ac.bris.cs.scotlandyard.ui.ai.tests;

import com.google.common.collect.AbstractIterator;
import com.google.common.collect.ImmutableList;
import io.atlassian.fugue.Pair;
import org.junit.Test;
import uk.ac.bris.cs.scotlandyard.model.*;
import uk.ac.bris.cs.scotlandyard.model.Board.GameState;
import uk.ac.bris.cs.scotlandyard.ui.ai.Moriarty;
import uk.ac.bris.cs.scotlandyard.ui.ai.tests.TestBase;

import java.util.concurrent.TimeUnit;

import static uk.ac.bris.cs.scotlandyard.model.Piece.Detective.BLUE;
import static uk.ac.bris.cs.scotlandyard.model.Piece.MrX.MRX;
import static uk.ac.bris.cs.scotlandyard.model.ScotlandYard.Ticket.*;
import static uk.ac.bris.cs.scotlandyard.model.ScotlandYard.defaultDetectiveTickets;


/**
 * Tests whether valid moves are generated by the game state
 */
public class MoriartyTest extends TestBase{

    Move.FunctionalVisitor<Integer> getDestination = new Move.FunctionalVisitor<>(m -> m.destination, m -> m.destination2);

    @Test public void testMrXAvoidsCatchableLocationsIfPossible() {

        var mrX = new Player(MRX, makeTickets(5, 0, 0, 0, 0), 166);
        var blue = new Player(BLUE, defaultDetectiveTickets(), 152);
        var green = new Player(BLUE, defaultDetectiveTickets(), 180);

        // only secret moves if only secret move ticket left
        GameState state = gameStateFactory.build(
                new GameSetup(standardGraph(), ImmutableList.of(true)),
                mrX, blue, green);

        Ai Moriarty = new Moriarty();

        assert(Moriarty.pickMove(state, new Pair<>(25L, TimeUnit.SECONDS)).visit(getDestination) == 183);
    }

}
